---
- name: OpenStack worker node configuration Tasks (i.e. Create worker.ign, Upload RHCOS Image, Create Customization Script, Create Instance etc)
  hosts: all
  vars_files:
    - ../vars/main.yml

  tasks:
  - name: Remove host aggregate (host group) from openstack
    openstack.cloud.host_aggregate:
      cloud: openstack
      state: absent
      name: "{{ host_aggregate_name }}"
       
      